name: qa.yml
on: 
  push: {}
  pull_request:
    branches:
      - main
    

jobs:
  format-and-lint-check:
    runs-on: ubuntu-22.04
    continue-on-error: ${{github.event_name == 'push' && github.event.action != 'synchronize'}}
    steps:
      - name: Log Event Names
        shell: bash
        run: echo "event: ${{github.event_name}} | event.action: ${{github.event.action}}"
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Run C# format checks
        shell: bash
        run: ./build.sh -t FormatCheck
  
  test:
    needs: format-and-lint-check
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Run C# Unit Tests
        shell: bash
        run: ./build.sh -t Test
        