name: qa.yml
on: push

jobs:
  format-and-lint-check:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Run Format Checks
        shell: bash
        run: ./build.sh -t FormatCheck
  
  test:
    needs: format-and-lint-check
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Run Unit Tests
        shell: bash
        run: ./build.sh -t Test
  
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Build Artifact
        shell: bash
        run: ./build.sh -t Publish